feign:
  hystrix:
    #开启Hystrix
    enabled: true

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 从服务器读取到可用资源所用的时间
  ReadTimeout: 3000
  # 建立连接所用的时间
  ConnectTimeout: 2000

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 4000

server-provider: SERVER-PROVIDER

data: dev9

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: root
    password: ligenhui
