feign:
  hystrix:
    #开启Hystrix
    enabled: true

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 从服务器读取到可用资源所用的时间
  ReadTimeout: 3000
  # 建立连接所用的时间
  ConnectTimeout: 2000

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 4000

server-provider: SERVER-PROVIDER

data: dev
